
const ewData =   [
  {
    "customerDetails.customerName": "BOJEDLA ARAVIND",
    "customerDetails.email": "bojedla.aravind@gmail.com",
    "customerDetails.pan": "AHIPB4225D",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 7093875742,
    "customerDetails.customerGst": 7093875742,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5CEA8H008763",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-13",
    "vehicleDetails.dealerLocation": "Gachibowli",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 220,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "PRADEEP BALUPATI",
    "vehicleDetails.rmEmployeeId": "MG1378",
    "vehicleDetails.rmEmail": "pradeep.b@mghyderabad.com",
    "vehicleDetails.gmEmail": "anupam.b@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RA140431"
  },
  {
    "customerDetails.customerName": "MAMIDI SETI VEERA VENKATA SATYANARAYANA",
    "customerDetails.email": "mvvs2106@gmail.com",
    "customerDetails.pan": "AOLPM2617L",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9908133996,
    "customerDetails.customerGst": 9908133996,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H010911",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-10",
    "vehicleDetails.dealerLocation": "Kukatpally",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": "55kms",
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Shaik Arshad",
    "vehicleDetails.rmEmployeeId": "MG1232",
    "vehicleDetails.rmEmail": "hyderabad.sc25@mgdealer.co.in",
    "vehicleDetails.gmEmail": "ravindra.k@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1R9300154"
  },
  {
    "customerDetails.customerName": "SIRIGIRI VIJAY KUMAR",
    "customerDetails.email": "Roheetsirigiri@gmail.com",
    "customerDetails.pan": "ATQPK0319K",
    "customerDetails.address": "13-3-55/A BADABANDA,,TelanganaMUSTAIDPURA",
    "customerDetails.contact": 8688641928,
    "customerDetails.customerGst": 8688641928,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H012109",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-26",
    "vehicleDetails.dealerLocation": "Banjara Hills",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 100,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "S.MADHAVI WAGH",
    "vehicleDetails.rmEmployeeId": "MG1670",
    "vehicleDetails.rmEmail": "hyderabad.sc103@mgdealer.co.in",
    "vehicleDetails.gmEmail": "Rishithanandyala@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RA300048"
  },
  {
    "customerDetails.customerName": "TUMU HIMA BINDU",
    "customerDetails.email": "hima.maggi88@gmail.com",
    "customerDetails.pan": "ALQPB2558M",
    "customerDetails.address": "PNO 3/A AND 19 PART GAFOOR NAGAR,,TelanganaNEAR IMAGE HOSPITAL LANE MADHAPUR",
    "customerDetails.contact": 9182521817,
    "customerDetails.customerGst": 9182521817,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H010182",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-07",
    "vehicleDetails.dealerLocation": "Kukatpally",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 45,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Shaik Arshad",
    "vehicleDetails.rmEmployeeId": "MG1232",
    "vehicleDetails.rmEmail": "hyderabad.sc25@mgdealer.co.in",
    "vehicleDetails.gmEmail": "ravindra.k@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RA230030"
  },
  {
    "customerDetails.customerName": "KOTHA MANIKANTA",
    "customerDetails.email": "447MANIKANTA.KOTHA@GMAIL.COM",
    "customerDetails.pan": "BRRPK5151P",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9885802638,
    "customerDetails.customerGst": 9885802638,
    "vehicleDetails.vehicleModel": "Astor",
    "vehicleDetails.vinNumber": "MZ7CD33KJ7H042690",
    "vehicleDetails.fuelType": "Petrol",
    "Validity Milage": "100K Kms",
    "vehicleDetails.deliveryDate": "2025-02-12",
    "vehicleDetails.dealerLocation": "Kondapur",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "23640",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 50,
    "ewDetails.startKm__1": "100K Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "G jeevan",
    "vehicleDetails.rmEmployeeId": 1392,
    "vehicleDetails.rmEmail": "hyderabad.sc54@mgdealer.co.in",
    "vehicleDetails.gmEmail": "bharath@mghyderabad.com",
    "vehicleDetails.engineNumber": "FMGR6030347"
  },
  {
    "customerDetails.customerName": "Vikram kishore reddy peri",
    "customerDetails.email": "dr.vikramperi@gmail.com",
    "customerDetails.pan": "BLWPP6205Q",
    "customerDetails.address": "3-353/MIG,,TelanganaMAYURI NAGAR MIYAPUR",
    "customerDetails.contact": "95027 35121",
    "customerDetails.customerGst": "95027 35121",
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H010296",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-03-03",
    "vehicleDetails.dealerLocation": "Gachibowli",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 60,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Karukundi srinu",
    "vehicleDetails.rmEmployeeId": "Mg1395",
    "vehicleDetails.rmEmail": "Hyderabad.sc69@mgdealer.co.in",
    "vehicleDetails.gmEmail": "anupam.b@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RA260040"
  },
  {
    "customerDetails.customerName": "MADHAVARAM KAVYA SREE",
    "customerDetails.email": "bhanu3999chander@gmail.com",
    "customerDetails.pan": "FGEPM7312A",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9966666707,
    "customerDetails.customerGst": 9966666707,
    "vehicleDetails.vehicleModel": "ZS EV",
    "vehicleDetails.vinNumber": "MZ7GD5DEG7H019793",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-07",
    "vehicleDetails.dealerLocation": "Kukatpally",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "42040",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 50,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Md Haji Baba",
    "vehicleDetails.rmEmployeeId": "MG0361",
    "vehicleDetails.rmEmail": "hyderabad.sc39@mgdealer.co.in",
    "vehicleDetails.gmEmail": "ravindra.k@mghyderabad.com",
    "vehicleDetails.engineNumber": "24403A10275272"
  },
  {
    "customerDetails.customerName": "Aggani pavan sagar",
    "customerDetails.email": "AGGANIPAVAN06@GMAIL.COM",
    "customerDetails.pan": "EASPA4107A",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9963000357,
    "customerDetails.customerGst": 9963000357,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H011968",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-28",
    "vehicleDetails.dealerLocation": "Kondapur",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": "50km",
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Darsha venu gopal",
    "vehicleDetails.rmEmployeeId": "MG1685",
    "vehicleDetails.rmEmail": "kukatpally.sc2@mgdealer.co.in",
    "vehicleDetails.gmEmail": "bharath@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RB050127"
  },
  {
    "customerDetails.customerName": "DIVYA REDDY GONGIREDDY",
    "customerDetails.email": "divyathodeti@gmail.com",
    "customerDetails.pan": "AFRPT3676B",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9885004999,
    "customerDetails.customerGst": 9885004999,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H010805",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-08",
    "vehicleDetails.dealerLocation": "Banjara Hills",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 21,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Bhanu sankar reddy pallapolu",
    "vehicleDetails.rmEmployeeId": "MG1977",
    "vehicleDetails.rmEmail": "hyderabad.sc47@mgdealer.co.in",
    "vehicleDetails.gmEmail": "Rishithanandyala@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RA170098"
  },
  {
    "customerDetails.customerName": "VAMSI KRISHNA BHIMAVARAPU",
    "customerDetails.email": "Bh.vamsi@gmail.com",
    "customerDetails.pan": "ARIPK4115D",
    "customerDetails.address": "1108 AVANI BLOCK GREEN GRACE APARTM,,TelanganaNEAR OAKRIDGE SCHOOL KHAJAGUDA",
    "customerDetails.contact": "90001 17754",
    "customerDetails.customerGst": "90001 17754",
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H009785",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-12",
    "vehicleDetails.dealerLocation": "Gachibowli",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 60,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Karukundi srinu",
    "vehicleDetails.rmEmployeeId": "Mg1395",
    "vehicleDetails.rmEmail": "Hyderabad.sc69@mgdealer.co.in",
    "vehicleDetails.gmEmail": "anupam.b@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RA140037"
  },
  {
    "customerDetails.customerName": "LAKSHMI CHANDRAKALA PATLURI",
    "customerDetails.email": "RSMUVVALA@GMAIL.COM",
    "customerDetails.pan": "APRPP4539D",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9553607755,
    "customerDetails.customerGst": 9553607755,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H012112",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-15",
    "vehicleDetails.dealerLocation": "Up Country",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 35,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "T.SRAVAN KUMAR",
    "vehicleDetails.rmEmployeeId": "MG1879",
    "vehicleDetails.rmEmail": "HYDERABAD.SC1@MGDEALER.CO.IN",
    "vehicleDetails.gmEmail": "balaji.p@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RA300052"
  },
  {
    "customerDetails.customerName": "KAMATALA MAHESHWAR",
    "customerDetails.email": "MAI.ESHWAR@GMAIL.COM",
    "customerDetails.pan": "BPNPK2111K",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9849161363,
    "customerDetails.customerGst": 9849161363,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H013418",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-14",
    "vehicleDetails.dealerLocation": "Kondapur Service",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 50,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "SHIVA KUMAR HULSUR",
    "vehicleDetails.rmEmployeeId": "MG1265",
    "vehicleDetails.rmEmail": "hyderabad.sc92@mgdealer.co.in",
    "vehicleDetails.gmEmail": "bharath@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RB250171"
  },
  {
    "customerDetails.customerName": "KANJARLA PRAKASH",
    "customerDetails.email": "rahulkumarkanjarla5544@gmail.com",
    "customerDetails.pan": "AJCPK1989M",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 7799825544,
    "customerDetails.customerGst": 7799825544,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H013275",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-17",
    "vehicleDetails.dealerLocation": "Kondapur",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 50,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Darsha venu gopal",
    "vehicleDetails.rmEmployeeId": "MG1685",
    "vehicleDetails.rmEmail": "kukatpally.sc2@mgdealer.co.in",
    "vehicleDetails.gmEmail": "bharath@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RB060109"
  },
  {
    "customerDetails.customerName": "KALLEPU RITHESH",
    "customerDetails.email": "kallepu.rithesh@gmail.com",
    "customerDetails.pan": "BZEPK7433F",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 910966633,
    "customerDetails.customerGst": 910966633,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H013456",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "100K Kms",
    "vehicleDetails.deliveryDate": "2025-02-17",
    "vehicleDetails.dealerLocation": "Attapur",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "20599",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 70,
    "ewDetails.startKm__1": "100K Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "MOHD KHAJA PASHA",
    "vehicleDetails.rmEmployeeId": 10029918,
    "vehicleDetails.rmEmail": "HYDERABAD.SC12@MGDEALER.CO.IN",
    "vehicleDetails.gmEmail": "Hreju.p@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RC100289"
  },
  {
    "customerDetails.customerName": "VENKATA NAGA DIKSHITA DHAVALA",
    "customerDetails.email": "yadavalli.karthik@gmail.com",
    "customerDetails.pan": "BMAPD7065B",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9652219988,
    "customerDetails.customerGst": 9652219988,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H013896",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-15",
    "vehicleDetails.dealerLocation": "Gachibowli",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 64,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "RAJASHEKAR",
    "vehicleDetails.rmEmployeeId": "Mg1768",
    "vehicleDetails.rmEmail": "hyderabad.sc65@mgdealer.co.in",
    "vehicleDetails.gmEmail": "anupam.b@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RB140169"
  },
  {
    "customerDetails.customerName": "SAJID HASSAN ALI DAMANI",
    "customerDetails.email": "britegenerator@yahoo.com",
    "customerDetails.pan": "AGZPD1614N",
    "customerDetails.address": "hyderabad,,Telangana",
    "customerDetails.contact": 9949655385,
    "customerDetails.customerGst": 9949655385,
    "vehicleDetails.vehicleModel": "Hector",
    "vehicleDetails.vinNumber": "MZ7DD1PPA7H132116",
    "vehicleDetails.fuelType": "Diesel",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-28",
    "vehicleDetails.dealerLocation": "Gachibowli",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "42740",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 500,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "PRADEEP BALUPATI",
    "vehicleDetails.rmEmployeeId": "MG1378",
    "vehicleDetails.rmEmail": "pradeep.b@mghyderabad.com",
    "vehicleDetails.gmEmail": "anupam.b@mghyderabad.com",
    "vehicleDetails.engineNumber": 463544604276350
  },
  {
    "customerDetails.customerName": "KURA DEEPAK RAYALU",
    "customerDetails.email": "deepakrayalu@gmail.com",
    "customerDetails.pan": "ARWPK7877L",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9989419420,
    "customerDetails.customerGst": 9989419420,
    "vehicleDetails.vehicleModel": "ZS EV",
    "vehicleDetails.vinNumber": "MZ7GD59EH7H020681",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-13",
    "vehicleDetails.dealerLocation": "Gachibowli",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "42040",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 500,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "PRADEEP BALUPATI",
    "vehicleDetails.rmEmployeeId": "MG1378",
    "vehicleDetails.rmEmail": "pradeep.b@mghyderabad.com",
    "vehicleDetails.gmEmail": "anupam.b@mghyderabad.com",
    "vehicleDetails.engineNumber": "24405A10275607"
  },
  {
    "customerDetails.customerName": "Viswanath Samudrala",
    "customerDetails.email": "viswanath.samudrala@gmail.com",
    "customerDetails.pan": "AABCI9186R",
    "customerDetails.address": "U-109 Aparna Cyberzon,,TelanganaNear Citizens Hospital",
    "customerDetails.contact": 7893996793,
    "customerDetails.customerGst": 7893996793,
    "vehicleDetails.vehicleModel": "Comet",
    "vehicleDetails.vinNumber": "MZ71DA9NJ7H015330",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-12",
    "vehicleDetails.dealerLocation": "Gachibowli",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "40540",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 250,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "BAIROJI SAIKIRAN CHARY",
    "vehicleDetails.rmEmployeeId": "MG1295",
    "vehicleDetails.rmEmail": "hyderabad.sc67@mgdealer.co.in",
    "vehicleDetails.gmEmail": "anupam.b@mghyderabad.com",
    "vehicleDetails.engineNumber": "HCR6194232"
  },
  {
    "customerDetails.customerName": "SYED KAREEMUDDIN",
    "customerDetails.email": "syedkareemuddin1@yahoo.com",
    "customerDetails.pan": "FVSPS3343J",
    "customerDetails.address": "10-2-289/115,,TelanganaSHANTHI NAGAR",
    "customerDetails.contact": 9700060001,
    "customerDetails.customerGst": 9700060001,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEB8H014495",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-19",
    "vehicleDetails.dealerLocation": "Banjara Hills",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 100,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "B. YASHASWI GOPAL",
    "vehicleDetails.rmEmployeeId": "MG0957",
    "vehicleDetails.rmEmail": "hyderabad.sc78@mgdealer.co.in",
    "vehicleDetails.gmEmail": "varun.p@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RB220177"
  },
  {
    "customerDetails.customerName": "Mohammed Asrar Raqeeb",
    "customerDetails.email": "ASRAR.RAQEEB@GMAIL.COM",
    "customerDetails.pan": "ALPPR7658P",
    "customerDetails.address": "4TH FLOOR Upperpally,Mohammed Abdul Raqeeb,TelanganaVTC Rajendra Nagar PO",
    "customerDetails.contact": 9000809669,
    "customerDetails.customerGst": 919000809669,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H013454",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-20",
    "vehicleDetails.dealerLocation": "Attapur",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 63,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Khaja pasha",
    "vehicleDetails.rmEmployeeId": "MG1629",
    "vehicleDetails.rmEmail": "pasha.k@mghyderabad.com",
    "vehicleDetails.gmEmail": "fom@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RC070110"
  },
  {
    "customerDetails.customerName": "SHRI NARSINGH CLOTH EMPORIUM PRIVATE LIMITED",
    "customerDetails.email": "ravi9949109531@gmail.com",
    "customerDetails.pan": "AAHCS2779L",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9949109531,
    "customerDetails.customerGst": 9949109531,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H013394",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-21",
    "vehicleDetails.dealerLocation": "Banjara Hills",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 55,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "A Satya Vamshi",
    "vehicleDetails.rmEmployeeId": "INT0492",
    "vehicleDetails.rmEmail": "deepak@mghyderabad.com",
    "vehicleDetails.gmEmail": "Rishithanandyala@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RB230072"
  },
  {
    "customerDetails.customerName": "SNIGDHA RANGINENI",
    "customerDetails.email": "snigdha.rao29@gmail.com",
    "customerDetails.pan": "BUFPR5768A",
    "customerDetails.address": "HYDERABAD,,TelanganaNEAR LOTUS POND,",
    "customerDetails.contact": "99663 40878",
    "customerDetails.customerGst": "99663 40878",
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H013767",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-22",
    "vehicleDetails.dealerLocation": "Gachibowli",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 60,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Karukundi srinu",
    "vehicleDetails.rmEmployeeId": "MG1395",
    "vehicleDetails.rmEmail": "Hyderabad.sc69@mgdealer.co.in",
    "vehicleDetails.gmEmail": "anupam.b@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RB060197"
  },
  {
    "customerDetails.customerName": "Vishva kanthi ys",
    "customerDetails.email": "anand_kumar_m@yahoo.co.in",
    "customerDetails.pan": "AFYPY4639N",
    "customerDetails.address": "C-510, C- BLOCK HILL CREST BY PACIF,,TelanganaPUPPALAGUDA, NEAR PRESTIGE HIGH FIELDS",
    "customerDetails.contact": 9703078253,
    "customerDetails.customerGst": 9703078253,
    "vehicleDetails.vehicleModel": "ZS EV",
    "vehicleDetails.vinNumber": "MZ7GD5AEA8H023891",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-24",
    "vehicleDetails.dealerLocation": "Gachibowli",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "42040",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 60,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Karukundi srinu",
    "vehicleDetails.rmEmployeeId": "Mg1395",
    "vehicleDetails.rmEmail": "Hyderabad.sc69@mgdealer.co.in",
    "vehicleDetails.gmEmail": "anupam.b@mghyderabad.com",
    "vehicleDetails.engineNumber": "24529A10279441"
  },
  {
    "customerDetails.customerName": "RAGHURAM PRASAD K",
    "customerDetails.email": "raghuramacharya@gmail.com",
    "customerDetails.pan": "AKJPR2488L",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": "96762 62995",
    "customerDetails.customerGst": "96762 62995",
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5CEB8H014276",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-23",
    "vehicleDetails.dealerLocation": "Kondapur",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 50,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Vangala Vamshidhar reddy",
    "vehicleDetails.rmEmployeeId": "INT0522",
    "vehicleDetails.rmEmail": "Vamshivangala101@gmail.com",
    "vehicleDetails.gmEmail": "bharath@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RB050155"
  },
  {
    "customerDetails.customerName": "SEERAPU ANIL KUMAR",
    "customerDetails.email": "ravianilseerapu@gmail.com",
    "customerDetails.pan": "CCSPS2755N",
    "customerDetails.address": "HYDERABAD,SEERAPU KRISHNA,Telangana",
    "customerDetails.contact": 9666660333,
    "customerDetails.customerGst": 9666660333,
    "vehicleDetails.vehicleModel": "ZS EV",
    "vehicleDetails.vinNumber": "MZ7GD5AEH7H020515",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-24",
    "vehicleDetails.dealerLocation": "Banjara Hills",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "42040",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 140,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "NALIGATI SHASHANK YADAV",
    "vehicleDetails.rmEmployeeId": "MG1605",
    "vehicleDetails.rmEmail": "hyderabad.sc111@mgdealer.co.in",
    "vehicleDetails.gmEmail": "ankit@mghyderabad.com",
    "vehicleDetails.engineNumber": "24403A10275480"
  },
  {
    "customerDetails.customerName": "MOHAMMAD SHAHBAZ KHAN",
    "customerDetails.email": "MDSHAHBAZKHAN35@GMAIL.COM",
    "customerDetails.pan": "DEMPK1736Q",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9493342786,
    "customerDetails.customerGst": 9493342786,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEB8H014302",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-23",
    "vehicleDetails.dealerLocation": "Gachibowli",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 60,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Mahesh Avula",
    "vehicleDetails.rmEmployeeId": "Mg1711",
    "vehicleDetails.rmEmail": "hyderabad.sc49@mgdealer.co.in",
    "vehicleDetails.gmEmail": "anupam.b@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1R9290123"
  },
  {
    "customerDetails.customerName": "KILARU VENKATESH",
    "customerDetails.email": "ramyankaraghupathi@gmail.com",
    "customerDetails.pan": "BURPK6436N",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9000519216,
    "customerDetails.customerGst": 9000519216,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5CEA8H013334",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-22",
    "vehicleDetails.dealerLocation": "Gachibowli",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 60,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Mahesh Avula",
    "vehicleDetails.rmEmployeeId": "MG1711",
    "vehicleDetails.rmEmail": "hyderabad.sc49@mgdealer.co.in",
    "vehicleDetails.gmEmail": "anupam.b@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RB230208"
  },
  {
    "customerDetails.customerName": "SP SOFTWARE PRIVATE LIMITED",
    "customerDetails.email": "jeyaram.sjp@gmail.com",
    "customerDetails.pan": "AACCS8407N",
    "customerDetails.address": "hyderabad,,Telangana",
    "customerDetails.contact": 9866133663,
    "customerDetails.customerGst": 9866133663,
    "vehicleDetails.vehicleModel": "Hector",
    "vehicleDetails.vinNumber": "MZ7DD3S1L7H150401",
    "vehicleDetails.fuelType": "Petrol",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-07",
    "vehicleDetails.dealerLocation": "Banjara Hills",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "39740",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 55,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "BHANUSANKAR REDDY PALLAPOLU",
    "vehicleDetails.rmEmployeeId": "MG1977",
    "vehicleDetails.rmEmail": "hyderabad.sc47@mgdealer.co.in",
    "vehicleDetails.gmEmail": "Rishithanandyala@mghyderabad.com",
    "vehicleDetails.engineNumber": "18R62120044"
  },
  {
    "customerDetails.customerName": "ALEKHYA NAGULLAPALLI",
    "customerDetails.email": "suryakiran450@yahoo.co.in",
    "customerDetails.pan": "AATPE3314Q",
    "customerDetails.address": "HNO 2-62/63/64 PART AYYAPPA SOCIETY,,TelanganaNEAR VEGETABLE MARKET",
    "customerDetails.contact": 9866342444,
    "customerDetails.customerGst": 9866342444,
    "vehicleDetails.vehicleModel": "Astor",
    "vehicleDetails.vinNumber": "MZ7CD35KA8H044880",
    "vehicleDetails.fuelType": "Petrol",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-07",
    "vehicleDetails.dealerLocation": "Banjara Hills",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "27640",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 60,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "VICTOR",
    "vehicleDetails.rmEmployeeId": "INT0456",
    "vehicleDetails.rmEmail": "hyderabad.sc47@mgdealer.co.in",
    "vehicleDetails.gmEmail": "Rishithanandyala@mghyderabad.com",
    "vehicleDetails.engineNumber": "FMGRA190139"
  },
  {
    "customerDetails.customerName": "TEJASWI MARNENI",
    "customerDetails.email": "VELAGAPUDIRAJ@GMAIL.COM",
    "customerDetails.pan": "BMTPM4889F",
    "customerDetails.address": "FNO 504 MIG-2 899/900,,TelanganaPARK VIEW ENCLAVE",
    "customerDetails.contact": 9959730280,
    "customerDetails.customerGst": 9959730280,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H012035",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "100k Kms",
    "vehicleDetails.deliveryDate": "2025-02-13",
    "vehicleDetails.dealerLocation": "Kondapur",
    "createdAt": "2025-03-24",
    "ewDetails.policyDate": "24 Jan 2025",
    "ewDetails.warrantyAmount": "11849",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 85,
    "ewDetails.startKm__1": "100k Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "G.jeevan",
    "vehicleDetails.rmEmployeeId": "MG1392",
    "vehicleDetails.rmEmail": "hyderabad.sc54@mgdealer.co.in",
    "vehicleDetails.gmEmail": "bharath@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1R9150070"
  },
  {
    "customerDetails.customerName": "ADUSUMILLI JYOTHI",
    "customerDetails.email": "Prassi@gmail.com",
    "customerDetails.pan": "AUAPA3139J",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9492304567,
    "customerDetails.customerGst": 9492304567,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H011956",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-13",
    "vehicleDetails.dealerLocation": "Gachibowli",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 0,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "ABDUL WASAY",
    "vehicleDetails.rmEmployeeId": 10030241,
    "vehicleDetails.rmEmail": "hyderabad.sc15@mgdealer.co.in",
    "vehicleDetails.gmEmail": "anupam.b@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RA220224"
  },
  {
    "customerDetails.customerName": "RACHARLA SOWMYA",
    "customerDetails.email": "UDAYARACHARLA@GMAIL.COM",
    "customerDetails.pan": "CXWPS0586G",
    "customerDetails.address": "Flat no : 508 , SHANTHI TRIKUTA RES,,TelanganaPRASHANTH NAGAR 100 FEET ROAD",
    "customerDetails.contact": 8688517707,
    "customerDetails.customerGst": 8688517707,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H009728",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-07",
    "vehicleDetails.dealerLocation": "Up Country",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 10,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Dhonika vijay chander",
    "vehicleDetails.rmEmployeeId": "MG0467",
    "vehicleDetails.rmEmail": "hyderabad.sc89@mgdealer.co.in",
    "vehicleDetails.gmEmail": "balaji.p@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RA070166"
  },
  {
    "customerDetails.customerName": "BANNARAVURI APARNA",
    "customerDetails.email": "aparna.bannaravuri@gmail.com",
    "customerDetails.pan": "CXKPB1367G",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9398836606,
    "customerDetails.customerGst": 9398836606,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H011868",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-07",
    "vehicleDetails.dealerLocation": "Kukatpally",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 50,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Md Haji Baba",
    "vehicleDetails.rmEmployeeId": "MG0361",
    "vehicleDetails.rmEmail": "hyderabad.sc39@mgdealer.co.in",
    "vehicleDetails.gmEmail": "ravindra.k@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1R9260060"
  },
  {
    "customerDetails.customerName": "CHAITANYA KRISHNA VIJAYAGIRI",
    "customerDetails.email": "vck009@gmail.com",
    "customerDetails.pan": "AMVPV0624J",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9989902116,
    "customerDetails.customerGst": 9989902116,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H013732",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-08",
    "vehicleDetails.dealerLocation": "Kondapur",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 60,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Shiva Kumar Hulsur",
    "vehicleDetails.rmEmployeeId": "MG1265",
    "vehicleDetails.rmEmail": "hyderabad.sc92@mgdealer.co.in",
    "vehicleDetails.gmEmail": "bharath@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RA290192"
  },
  {
    "customerDetails.customerName": "WITT INDIA PRIVATE LIMITED",
    "customerDetails.email": "ld@wittindia.com",
    "customerDetails.pan": "AAACW7441E",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 8886114703,
    "customerDetails.customerGst": 8886114703,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H013397",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-19",
    "vehicleDetails.dealerLocation": "Kondapur",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 50,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "SHIVA KUMAR HULSUR",
    "vehicleDetails.rmEmployeeId": "MG1265",
    "vehicleDetails.rmEmail": "hyderabad.sc92@mgdealer.co.in",
    "vehicleDetails.gmEmail": "bharath@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RB260118"
  },
  {
    "customerDetails.customerName": "IDISHA INFO LABS PRIVATE LIMITED",
    "customerDetails.email": "KNMRAO@QUICKRIDE.IN",
    "customerDetails.pan": "AAACS4944A",
    "customerDetails.address": "FNO-102,BUILDING NO-545,,TelanganaSRI RAM CASTLE SRI RAM NAGAR COLONY",
    "customerDetails.contact": 8341190423,
    "customerDetails.customerGst": 8341190423,
    "vehicleDetails.vehicleModel": "ZS EV",
    "vehicleDetails.vinNumber": "MZ7GD5BEL7H023358",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-11",
    "vehicleDetails.dealerLocation": "Kondapur",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "42040",
    "ewDetails.planType": "Type B",
    "ewDetails.planSubType": "Standard",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 100,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Shiva Kumar Hulsur",
    "vehicleDetails.rmEmployeeId": "MG1265",
    "vehicleDetails.rmEmail": "hyderabad.sc92@mgdealer.co.in",
    "vehicleDetails.gmEmail": "bharath@mghyderabad.com",
    "vehicleDetails.engineNumber": "24619A10282616"
  },
  {
    "customerDetails.customerName": "IDISHA INFO LABS PRIVATE LIMITED",
    "customerDetails.email": "KNMRAO@QUICKRIDE.IN",
    "customerDetails.pan": "AAACS4944A",
    "customerDetails.address": "FNO-102,BUILDING NO-545,,TelanganaSRI RAM CASTLE SRI RAM NAGAR COLONY",
    "customerDetails.contact": 8341190423,
    "customerDetails.customerGst": 8341190423,
    "vehicleDetails.vehicleModel": "ZS EV",
    "vehicleDetails.vinNumber": "MZ7GD5BEL7H023390",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-11",
    "vehicleDetails.dealerLocation": "Kondapur",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "42040",
    "ewDetails.planType": "Type B",
    "ewDetails.planSubType": "Standard",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 100,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "SHIVA KUMAR HULSUR",
    "vehicleDetails.rmEmployeeId": "MG12656",
    "vehicleDetails.rmEmail": "hyderabad.sc92@mgdealer.co.in",
    "vehicleDetails.gmEmail": "bharath@mghyderabad.com",
    "vehicleDetails.engineNumber": "24531A10279906"
  },
  {
    "customerDetails.customerName": "IDISHA INFO LABS PRIVATE LIMITED",
    "customerDetails.email": "KNMRAO@QUICKRIDE.IN",
    "customerDetails.pan": "AAACS4944A",
    "customerDetails.address": "FNO-102,BUILDING NO-545,,TelanganaSRI RAM CASTLE SRI RAM NAGAR COLONY",
    "customerDetails.contact": 8341190423,
    "customerDetails.customerGst": 8341190423,
    "vehicleDetails.vehicleModel": "ZS EV",
    "vehicleDetails.vinNumber": "MZ7GD5BEL7H023316",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-11",
    "vehicleDetails.dealerLocation": "Kukatpally",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "42040",
    "ewDetails.planType": "Type B",
    "ewDetails.planSubType": "Standard",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 100,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "SHIVA KUMAR HULSUR",
    "vehicleDetails.rmEmployeeId": "MG1265",
    "vehicleDetails.rmEmail": "hyderabad.sc92@mgdealer.co.in",
    "vehicleDetails.gmEmail": "ravindra.k@mghyderabad.com",
    "vehicleDetails.engineNumber": "24610A10281428"
  },
  {
    "customerDetails.customerName": "IDISHA INFO LABS PRIVATE LIMITED",
    "customerDetails.email": "KNMRAO@QUICKRIDE.IN",
    "customerDetails.pan": "AAACS4944A",
    "customerDetails.address": "FNO-102,BUILDING NO-545,,TelanganaSRI RAM CASTLE SRI RAM NAGAR COLONY",
    "customerDetails.contact": 8341190423,
    "customerDetails.customerGst": 8341190423,
    "vehicleDetails.vehicleModel": "ZS EV",
    "vehicleDetails.vinNumber": "MZ7GD5BEL7H023340",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-11",
    "vehicleDetails.dealerLocation": "Kondapur",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "42040",
    "ewDetails.planType": "Type B",
    "ewDetails.planSubType": "Standard",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 100,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "SHIVA KUMAR HULSUR",
    "vehicleDetails.rmEmployeeId": "MG1265",
    "vehicleDetails.rmEmail": "hyderabad.sc92@mgdealer.co.in",
    "vehicleDetails.gmEmail": "bharath@mghyderabad.com",
    "vehicleDetails.engineNumber": "24616A10282487"
  },
  {
    "customerDetails.customerName": "IDISHA INFO LABS PRIVATE LIMITED",
    "customerDetails.email": "KNMRAO@QUICKRIDE.IN",
    "customerDetails.pan": "AAACS4944A",
    "customerDetails.address": "FNO-102,BUILDING NO-545,,TelanganaSRI RAM CASTLE SRI RAM NAGAR COLONY",
    "customerDetails.contact": 8341190423,
    "customerDetails.customerGst": 8341190423,
    "vehicleDetails.vehicleModel": "ZS EV",
    "vehicleDetails.vinNumber": "MZ7GD5BEL7H023348",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-11",
    "vehicleDetails.dealerLocation": "Kukatpally",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "42040",
    "ewDetails.planType": "Type B",
    "ewDetails.planSubType": "Standard",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 100,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "SHIVA KUMAR HUSLUR",
    "vehicleDetails.rmEmployeeId": "MG1265",
    "vehicleDetails.rmEmail": "hyderabad.sc92@mgdealer.co.in",
    "vehicleDetails.gmEmail": "ravindra.k@mghyderabad.com",
    "vehicleDetails.engineNumber": "24807A10283094"
  },
  {
    "customerDetails.customerName": "HARISH KANDALAM",
    "customerDetails.email": "kandalamharish.tlp@gmail.com",
    "customerDetails.pan": "DRRPK9838M",
    "customerDetails.address": "9-111/26/A/1 ROAD NO-7,,TelanganaANJANEYA NAGAR COLONY",
    "customerDetails.contact": 9581490906,
    "customerDetails.customerGst": 9581490906,
    "vehicleDetails.vehicleModel": "Hector",
    "vehicleDetails.vinNumber": "MZ7DD3S1G7H146061",
    "vehicleDetails.fuelType": "Petrol",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-24",
    "vehicleDetails.dealerLocation": "Banjara Hills",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "39740",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 75,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "B. YASHASWI GOPAL",
    "vehicleDetails.rmEmployeeId": "MG0957",
    "vehicleDetails.rmEmail": "hyderabad.sc78@mgdealer.co.in",
    "vehicleDetails.gmEmail": "varun.p@mghyderabad.com",
    "vehicleDetails.engineNumber": "18R40220641"
  },
  {
    "customerDetails.customerName": "Veturi Vijaya Lakshmi",
    "customerDetails.email": "Vijayadurgatraders31@gmail.com",
    "customerDetails.pan": "ADSPV2862J",
    "customerDetails.address": "MIGH-2 MOSSAPET, BHARAT NAGAR, BALN,,TelanganaRANGAREDDY",
    "customerDetails.contact": 9848999637,
    "customerDetails.customerGst": 9848999637,
    "vehicleDetails.vehicleModel": "Gloster",
    "vehicleDetails.vinNumber": "MZ7JD64JA8H011409",
    "vehicleDetails.fuelType": "Diesel",
    "Validity Milage": "100K Kms",
    "vehicleDetails.deliveryDate": "2025-02-23",
    "vehicleDetails.dealerLocation": "Attapur",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "71648",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 85,
    "ewDetails.startKm__1": "100K Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Kamitikari Pavan Kalyan",
    "vehicleDetails.rmEmployeeId": "MG1010",
    "vehicleDetails.rmEmail": "Hyderabadkon.sa1@mgdealer.co.in",
    "vehicleDetails.gmEmail": "Hreju.p@mghyderabad.com",
    "vehicleDetails.engineNumber": "M9236051369"
  },
  {
    "customerDetails.customerName": "VENKATA KARUNAKARA RAO BOLIMERA",
    "customerDetails.email": "theforminc@gmail.com",
    "customerDetails.pan": "AIYPB7119B",
    "customerDetails.address": "HYDERABAD,,Andhra Pradesh",
    "customerDetails.contact": 9989666775,
    "customerDetails.customerGst": 9989666775,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H010586",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-20",
    "vehicleDetails.dealerLocation": "Banjara Hills",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 100,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Chinthala vinith Reddy",
    "vehicleDetails.rmEmployeeId": "MG1946",
    "vehicleDetails.rmEmail": "hyderabad.sc27@mgdealer.co.in",
    "vehicleDetails.gmEmail": "Rishithanandyala@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RA140276"
  },
  {
    "customerDetails.customerName": "LIKHITHA GUMMALLA",
    "customerDetails.email": "gummallalikhitha92.eee@gmail.com",
    "customerDetails.pan": "BNVPG4023L",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9000205485,
    "customerDetails.customerGst": 9000205485,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H010162",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-10",
    "vehicleDetails.dealerLocation": "Kondapur",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 50,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Vamshidhar reddy",
    "vehicleDetails.rmEmployeeId": "INT0522",
    "vehicleDetails.rmEmail": "vamshivangala101@gmail.com",
    "vehicleDetails.gmEmail": "bharath@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RA140201"
  },
  {
    "customerDetails.customerName": "RIKAB CHAND",
    "customerDetails.email": "NAVEENPARAK@HOTMAIL.COM",
    "customerDetails.pan": "ABBPC4610Q",
    "customerDetails.address": "8-2-293/82/A PLOT NO 1092, ROAD NO,,TelanganaJUBLIEE HILLS",
    "customerDetails.contact": 9396532264,
    "customerDetails.customerGst": 9396532264,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H012644",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-21",
    "vehicleDetails.dealerLocation": "Kondapur",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 100,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "SHIVA KUMAR HULSUR",
    "vehicleDetails.rmEmployeeId": "MG1265",
    "vehicleDetails.rmEmail": "hyderabad.sc92@mgdealer.co.in",
    "vehicleDetails.gmEmail": "bharath@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RB140121"
  },
  {
    "customerDetails.customerName": "L GIRDHARILAL & CO",
    "customerDetails.email": "LGIRDHARILALCO@GMAIL.COM",
    "customerDetails.pan": "AABFL0305Q",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9885671061,
    "customerDetails.customerGst": 9885671061,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEB8H015300",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-28",
    "vehicleDetails.dealerLocation": "Kondapur",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 0,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Syed amaan",
    "vehicleDetails.rmEmployeeId": "INT0474",
    "vehicleDetails.rmEmail": "amaansyed478@gmail.com",
    "vehicleDetails.gmEmail": "bharath@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RC300171"
  },
  {
    "customerDetails.customerName": "SHIVNARAYAN JEWELLERS PRIVATE LIMITED",
    "customerDetails.email": "ACCOUNTS@SHIVNARAYANJEWELLERS.COM",
    "customerDetails.pan": "AASCS4695N",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": "91001 00180",
    "customerDetails.customerGst": "91001 00180",
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H014024",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-17",
    "vehicleDetails.dealerLocation": "Kondapur",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 0,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Syed amaan",
    "vehicleDetails.rmEmployeeId": "INT0474",
    "vehicleDetails.rmEmail": "amaansyed478@gmail.com",
    "vehicleDetails.gmEmail": "bharath@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RB060125"
  },
  {
    "customerDetails.customerName": "BOKKA ANITHA",
    "customerDetails.email": "ANITHAMADIREDDY@GMAIL.COM",
    "customerDetails.pan": "AGUPB7449L",
    "customerDetails.address": "VILLA NO 48 LEGEND CHIMES ECHO, PIP,,TelanganaKOKAPET RANGA REDDY",
    "customerDetails.contact": 9849625672,
    "customerDetails.customerGst": 9849625672,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5CEA8H008705",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-27",
    "vehicleDetails.dealerLocation": "Gachibowli",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 61,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "ANJANIKUMAR NAIK BANAVATHU",
    "vehicleDetails.rmEmployeeId": "INT0466",
    "vehicleDetails.rmEmail": "hyderabad.sc116@mgdealer.co.in",
    "vehicleDetails.gmEmail": "anupam.b@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1R9180118"
  },
  {
    "customerDetails.customerName": "KYASA MURALIDHAR",
    "customerDetails.email": "kyasajewellers2015@gmail.com",
    "customerDetails.pan": "ARDPK4725A",
    "customerDetails.address": "SECUNDERABAD,,Telangana",
    "customerDetails.contact": 9000222220,
    "customerDetails.customerGst": 9000222220,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H013729",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-28",
    "vehicleDetails.dealerLocation": "Gachibowli",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 65,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "RAJASHEKAR",
    "vehicleDetails.rmEmployeeId": "MG1768",
    "vehicleDetails.rmEmail": "hyderabad.sc65@mgdealer.co.in",
    "vehicleDetails.gmEmail": "anupam.b@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RB250131"
  },
  {
    "customerDetails.customerName": "Nidhi Vijaywargi",
    "customerDetails.email": "vijayhrishita11@gmail.com",
    "customerDetails.pan": "AKNPV5028N",
    "customerDetails.address": "8-2-684/5/10 ROAD NO 12,,TelanganaBANJARA HILLS OPP TO ROCK ROOF",
    "customerDetails.contact": 9398137361,
    "customerDetails.customerGst": 9398137361,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H010231",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-27",
    "vehicleDetails.dealerLocation": "Banjara Hills",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 100,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "satya vamsi allam",
    "vehicleDetails.rmEmployeeId": "int0492",
    "vehicleDetails.rmEmail": "hyderabad.sc27@mgdealer.co.in",
    "vehicleDetails.gmEmail": "Rishithanandyala@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RA090175"
  },
  {
    "customerDetails.customerName": "VENNAPUSA HEMANTH REDDY",
    "customerDetails.email": "RAMMOHANA_9@YAHOO.COM",
    "customerDetails.pan": "AXPPV4733K",
    "customerDetails.address": "FNO 1112 BLOCK 6,,TelanganaMY HOME MANGALA",
    "customerDetails.contact": 9866626187,
    "customerDetails.customerGst": 9866626187,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEB8H014949",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-28",
    "vehicleDetails.dealerLocation": "Kondapur",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 50,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "SHIVA KUMAR HULSUR",
    "vehicleDetails.rmEmployeeId": "MG1265",
    "vehicleDetails.rmEmail": "hyderabad.sc92@mgdealer.co.in",
    "vehicleDetails.gmEmail": "bharath@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1R9300076"
  },
  {
    "customerDetails.customerName": "Srikanth Paleti",
    "customerDetails.email": "drsrik6@gmail.com",
    "customerDetails.pan": "AMFPP4340R",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9652245699,
    "customerDetails.customerGst": 9652245699,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5CEA8H013446",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-28",
    "vehicleDetails.dealerLocation": "Kondapur",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 50,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Vanaga vamshidhar reddy",
    "vehicleDetails.rmEmployeeId": "INT0522",
    "vehicleDetails.rmEmail": "hyderabad.sc55@mgdealer.co.in",
    "vehicleDetails.gmEmail": "bharath@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RC090021"
  },
  {
    "customerDetails.customerName": "NIMMALA ALEKHYA",
    "customerDetails.email": "Alekhayn35@gamil.com",
    "customerDetails.pan": "AGJPN0832G",
    "customerDetails.address": "HYDERABAD,,TelanganaGANDIPET",
    "customerDetails.contact": 9160001435,
    "customerDetails.customerGst": 9160001435,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5CEA8H012693",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-28",
    "vehicleDetails.dealerLocation": "Banjara Hills",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 60,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Naligati Shashank yadav",
    "vehicleDetails.rmEmployeeId": "MG1605",
    "vehicleDetails.rmEmail": "hyderabad.sc111@mgdealer.co.in",
    "vehicleDetails.gmEmail": "Rishithanandyala@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RB220142"
  },
  {
    "customerDetails.customerName": "MANJUNATH BHATT",
    "customerDetails.email": "V.MANJUNATHBHATT@GMAIL.COM",
    "customerDetails.pan": "BLDPB4744F",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9030076646,
    "customerDetails.customerGst": 9030076646,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEB8H015366",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-28",
    "vehicleDetails.dealerLocation": "Gachibowli",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 60,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "ANJANIKUMAR NAIK BANAVATHU",
    "vehicleDetails.rmEmployeeId": "INT0466",
    "vehicleDetails.rmEmail": "hyderabad.sc116@mgdealer.co.in",
    "vehicleDetails.gmEmail": "anupam.b@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RC200143"
  },
  {
    "customerDetails.customerName": "Sumeru sales Pvt ltd",
    "customerDetails.email": "Sumerusales123@gmail.con",
    "customerDetails.pan": "AAGCS3297N",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9848935789,
    "customerDetails.customerGst": 9848935789,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H013599",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-18",
    "vehicleDetails.dealerLocation": "Kukatpally",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 50,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "MANISH",
    "vehicleDetails.rmEmployeeId": "MG1680",
    "vehicleDetails.rmEmail": "hyderabad.sc109@mgdealer.co.in",
    "vehicleDetails.gmEmail": "ravindra.k@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RB140181"
  },
  {
    "customerDetails.customerName": "AKKELADEVI MAHESH",
    "customerDetails.email": "Chandrasekhar3634@gmail.com",
    "customerDetails.pan": "EFHPM1458C",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9160237714,
    "customerDetails.customerGst": 9160237714,
    "vehicleDetails.vehicleModel": "Hector",
    "vehicleDetails.vinNumber": "MZ7DD3M1A8H152374",
    "vehicleDetails.fuelType": "Petrol",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-26",
    "vehicleDetails.dealerLocation": "Banjara Hills",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "39740",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 100,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Sai Bhargav Pasupuleti",
    "vehicleDetails.rmEmployeeId": "MG1815",
    "vehicleDetails.rmEmail": "hyderabad.evm@mgdealer.co.in",
    "vehicleDetails.gmEmail": "varun.p@mghyderabad.com",
    "vehicleDetails.engineNumber": "18RB2620568"
  },
  {
    "customerDetails.customerName": "MOHAMMED MOHSIN AZAM",
    "customerDetails.email": "healthcarejaundice@gmail.com",
    "customerDetails.pan": "AMAPM3231F",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9502571440,
    "customerDetails.customerGst": 9502571440,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEB8H015242",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-28",
    "vehicleDetails.dealerLocation": "Kukatpally",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 41,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "MOHAMMED ABDUL KHALIQ",
    "vehicleDetails.rmEmployeeId": "MG1114",
    "vehicleDetails.rmEmail": "hyderabad.sc85@mgdealer.co.in",
    "vehicleDetails.gmEmail": "ravindra.k@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RC190045"
  },
  {
    "customerDetails.customerName": "NUGUR ASHOK KUMAR",
    "customerDetails.email": "Padmanugur@gmail.com",
    "customerDetails.pan": "ABMPN3325Q",
    "customerDetails.address": "F NOlG1 MYM ESTATES THAKUR MASION L,,TelanganaBESIDE KHAZANA JEWELLERS SOMAJIGUDA",
    "customerDetails.contact": 9391047083,
    "customerDetails.customerGst": 9391047083,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEB8H014363",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-27",
    "vehicleDetails.dealerLocation": "Banjara Hills",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 100,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Sai Bhargav Pasupuleti",
    "vehicleDetails.rmEmployeeId": "MG1815",
    "vehicleDetails.rmEmail": "hyderabad.evm@mgdealer.co.in",
    "vehicleDetails.gmEmail": "Rishithanandyala@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1R9240088"
  },
  {
    "customerDetails.customerName": "Ruchi Malhotra",
    "customerDetails.email": "Sachd13@gmail.com",
    "customerDetails.pan": "BVRPM7090K",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9705550078,
    "customerDetails.customerGst": 9705550078,
    "vehicleDetails.vehicleModel": "Hector",
    "vehicleDetails.vinNumber": "MZ7HD3S1L7H150045",
    "vehicleDetails.fuelType": "Petrol",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-28",
    "vehicleDetails.dealerLocation": "Banjara Hills",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "39740",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 100,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Sai Bhargav Pasupuleti",
    "vehicleDetails.rmEmployeeId": "MG1815",
    "vehicleDetails.rmEmail": "hyderabad.evm@mgdealer.co.in",
    "vehicleDetails.gmEmail": "varun.p@mghyderabad.com",
    "vehicleDetails.engineNumber": "18R60820059"
  },
  {
    "customerDetails.customerName": "YERVALA JITHENDAR REDDY",
    "customerDetails.email": "JITHENDER14684@GMAIL.COM",
    "customerDetails.pan": "ACJPY7281J",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9704679529,
    "customerDetails.customerGst": 9704679529,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEB8H015425",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-28",
    "vehicleDetails.dealerLocation": "Gachibowli",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 30,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Mahesh Avula",
    "vehicleDetails.rmEmployeeId": "MG1711",
    "vehicleDetails.rmEmail": "hyderabad.sc49@mgdealer.co.in",
    "vehicleDetails.gmEmail": "anupam.b@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1S1030480"
  },
  {
    "customerDetails.customerName": "Bingi naresh babu",
    "customerDetails.email": "bnaresh9@gmail.com",
    "customerDetails.pan": "AABCI9186R",
    "customerDetails.address": "Flat 502 Sita Towers Street No 11,,TelanganaHimayath Nagar Hyderabad",
    "customerDetails.contact": 9676826309,
    "customerDetails.customerGst": 9676826309,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEB8H015372",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-28",
    "vehicleDetails.dealerLocation": "Banjara Hills",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 100,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "Chinthala Vinith Reddy",
    "vehicleDetails.rmEmployeeId": "MG1946",
    "vehicleDetails.rmEmail": "hyderabad.sc27@mgdealer.co.in",
    "vehicleDetails.gmEmail": "Rishithanandyala@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RA090010"
  },
  {
    "customerDetails.customerName": "KATKAM AVINASH KUMAR",
    "customerDetails.email": "Avinashkatkam47@gmail.com",
    "customerDetails.pan": "BJMPK4780K",
    "customerDetails.address": "Kokapet,,Telangana",
    "customerDetails.contact": 8106585922,
    "customerDetails.customerGst": 8106585922,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H010113",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-23",
    "vehicleDetails.dealerLocation": "Gachibowli",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 400,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "PRADEEP BALUPATI",
    "vehicleDetails.rmEmployeeId": "MG1378",
    "vehicleDetails.rmEmail": "pradeep.b@mghyderabad.com",
    "vehicleDetails.gmEmail": "anupam.b@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RA070147"
  },
  {
    "customerDetails.customerName": "VARIKUPPALA VISHNUVARDHAN",
    "customerDetails.email": "vvarikuppalavishnuvardhan0@gmail.com",
    "customerDetails.pan": "CCCPV6664F",
    "customerDetails.address": "HYDERABAD,,Telangana",
    "customerDetails.contact": 9347633136,
    "customerDetails.customerGst": 9347633136,
    "vehicleDetails.vehicleModel": "Windsor",
    "vehicleDetails.vinNumber": "MZ72D5EEA8H014023",
    "vehicleDetails.fuelType": "Electric Vehicle",
    "Validity Milage": "UNL Kms",
    "vehicleDetails.deliveryDate": "2025-02-18",
    "vehicleDetails.dealerLocation": "Gachibowli",
    "createdAt": "2025-03-26",
    "ewDetails.policyDate": "26 Jan 2025",
    "ewDetails.warrantyAmount": "40860",
    "ewDetails.planType": "Type A",
    "ewDetails.planSubType": "Comprehensive",
    "vehicleDetails.registrationType": "Private",
    "ewDetails.startKm": 210,
    "ewDetails.startKm__1": "UNL Kms",
    "ewStatus": "pending",
    "vehicleDetails.rmName": "PRADEEP BALUPATI",
    "vehicleDetails.rmEmployeeId": "MG1378",
    "vehicleDetails.rmEmail": "pradeep.b@mghyderabad.com",
    "vehicleDetails.gmEmail": "anupam.b@mghyderabad.com",
    "vehicleDetails.engineNumber": "U1RB060099"
  }
]
module.exports = ewData